# Generated by Django 3.0.6 on 2020-06-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0002_auto_20200610_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
